In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so

In [47]:
df = pd.concat([pd.read_csv('data/Fraudulent_E-Commerce_Transaction_Data.csv'), pd.read_csv('data/Fraudulent_E-Commerce_Transaction_Data_2.csv')], ignore_index=True)
df

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
0,15d2e414-8735-46fc-9e02-80b472b2580f,d1b87f62-51b2-493b-ad6a-77e0fe13e785,58.09,2024-02-20 05:58:41,bank transfer,electronics,1,17,Amandaborough,tablet,212.195.49.198,Unit 8934 Box 0058\nDPO AA 05437,Unit 8934 Box 0058\nDPO AA 05437,0,30,5
1,0bfee1a0-6d5e-40da-a446-d04e73b1b177,37de64d5-e901-4a56-9ea0-af0c24c069cf,389.96,2024-02-25 08:09:45,debit card,electronics,2,40,East Timothy,desktop,208.106.249.121,"634 May Keys\nPort Cherylview, NV 75063","634 May Keys\nPort Cherylview, NV 75063",0,72,8
2,e588eef4-b754-468e-9d90-d0e0abfc1af0,1bac88d6-4b22-409a-a06b-425119c57225,134.19,2024-03-18 03:42:55,PayPal,home & garden,2,22,Davismouth,tablet,76.63.88.212,"16282 Dana Falls Suite 790\nRothhaven, IL 15564","16282 Dana Falls Suite 790\nRothhaven, IL 15564",0,63,3
3,4de46e52-60c3-49d9-be39-636681009789,2357c76e-9253-4ceb-b44e-ef4b71cb7d4d,226.17,2024-03-16 20:41:31,bank transfer,clothing,5,31,Lynnberg,desktop,207.208.171.73,"828 Strong Loaf Apt. 646\nNew Joshua, UT 84798","828 Strong Loaf Apt. 646\nNew Joshua, UT 84798",0,124,20
4,074a76de-fe2d-443e-a00c-f044cdb68e21,45071bc5-9588-43ea-8093-023caec8ea1c,121.53,2024-01-15 05:08:17,bank transfer,clothing,2,51,South Nicole,tablet,190.172.14.169,"29799 Jason Hills Apt. 439\nWest Richardtown, ...","29799 Jason Hills Apt. 439\nWest Richardtown, ...",0,158,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1496581,d8b7171f-bdd9-479c-b98b-396c621aebfe,98a3d94c-dc9a-4525-b273-e6ffe54cc5a4,53.73,2024-01-26 16:25:05,PayPal,toys & games,5,32,Rebeccafurt,tablet,173.97.197.128,USNV Clayton\r\nFPO AE 82639,USNV Clayton\r\nFPO AE 82639,0,363,16
1496582,0fd12cf3-c641-4499-8de1-15dc4555cb0c,b3429f52-8b27-46b5-914c-4accd989edb4,47.42,2024-02-25 17:03:26,credit card,clothing,4,41,Nataliefort,desktop,133.222.22.48,"9288 Patricia Cape Apt. 527\r\nMelissaton, IL ...","9288 Patricia Cape Apt. 527\r\nMelissaton, IL ...",0,296,17
1496583,649680d3-a684-44cb-95bf-9b454c3aa86d,066e25c9-4420-4224-bc3f-1a462708090e,1045.23,2024-03-28 23:46:47,bank transfer,health & beauty,1,9,East Shannonville,tablet,206.133.237.168,3015 Elizabeth Summit Suite 819\r\nEast Joelfo...,3015 Elizabeth Summit Suite 819\r\nEast Joelfo...,0,329,23
1496584,c10dbb08-28fc-4ec1-9850-d4e98d2b9640,cde96e9c-f562-4b8c-8fa8-f356f474232b,34.25,2024-02-09 11:29:18,debit card,home & garden,2,39,Lake Nicole,mobile,16.204.137.130,"531 Brittany Pike\r\nNew Stacy, OR 87952","531 Brittany Pike\r\nNew Stacy, OR 87952",0,347,11
1496585,23e3c107-f2fc-48c2-abbc-7b809bf6f102,d8d7a64e-8419-4421-910a-a7cf709a900b,85.03,2024-01-23 02:46:52,credit card,clothing,4,38,Holtport,tablet,116.188.254.162,"289 Adams Wells\r\nWest Joeltown, LA 69190","289 Adams Wells\r\nWest Joeltown, LA 69190",0,203,2

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1496586 entries, 0 to 1496585
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Transaction ID      1496586 non-null  object
 1   Customer ID         1496586 non-null  object
 2   Transaction Amount  1496586 non-null  float64
 3   Transaction Date    1496586 non-null  object
 4   Payment Method      1496586 non-null  object
 5   Product Category    1496586 non-null  object
 6   Quantity            1496586 non-null  int64
 7   Customer Age        1496586 non-null  int64
 8   Customer Location   1496586 non-null  object
 9   Device Used         1496586 non-null  object
 10  IP Address          1496586 non-null  object
 11  Shipping Address    1496586 non-null  object
 12  Billing Address     1496586 non-null  object
 13  Is Fraudulent       1496586 non-null  int64
 14  Account Age Days    1496586 non-null  int64
 15  Transaction Hour    1496586 non-null  int64
dtypes: float64(1), int64(5), object(10)
memory usage: 182.7+ MB

In [49]:
df.drop_duplicates(inplace=True)
df.drop(columns=['Transaction ID', 'Customer ID', 'IP Address'], inplace=True)

In [51]:
df.describe()

,Transaction Amount,Quantity,Customer Age,Is Fraudulent,Account Age Days,Transaction Hour
count,1.496586e+06,1.496586e+06,1.496586e+06,1.496586e+06,1.496586e+06,1.496586e+06
mean,2.268093e+02,3.000235e+00,3.451284e+01,5.015415e-02,1.796308e+02,1.128663e+01
std,2.705831e+02,1.414814e+00,1.000323e+01,2.182630e-01,1.068726e+02,6.976067e+00
min,1.000000e+01,1.000000e+00,-1.600000e+01,0.000000e+00,1.000000e+00,0.000000e+00
25%,6.862000e+01,2.000000e+00,2.800000e+01,0.000000e+00,8.600000e+01,5.000000e+00
50%,1.517600e+02,3.000000e+00,3.500000e+01,0.000000e+00,1.790000e+02,1.100000e+01
75%,2.960500e+02,4.000000e+00,4.100000e+01,0.000000e+00,2.720000e+02,1.700000e+01
max,1.270175e+04,5.000000e+00,8.600000e+01,1.000000e+00,3.650000e+02,2.300000e+01

In [52]:
for col in df.columns:
    print(f"\n{df[col].value_counts()}\n")

Transaction Amount
12.00      103
19.22      100
14.85       97
12.53       96
10.96       95
          ...
699.34       1
3387.20      1
1036.94      1
851.99       1
1045.23      1
Name: count, Length: 109503, dtype: int64


Transaction Date
2024-01-27 04:00:16    6
2024-01-06 19:59:37    5
2024-03-15 16:22:08    5
2024-01-05 02:14:55    5
2024-01-18 18:44:25    5
                      ..
2024-01-16 09:46:35    1
2024-03-10 22:48:20    1
2024-02-02 16:42:01    1
2024-01-23 10:53:57    1
2024-01-23 02:46:52    1
Name: count, Length: 1366540, dtype: int64


Payment Method
credit card      374352
debit card       374229
bank transfer    374138
PayPal           373867
Name: count, dtype: int64


Product Category
electronics        300042
health & beauty    300038
clothing           299018
toys & games       298996
home & garden      298492
Name: count, dtype: int64


Quantity
5    300003
3    299641
1    299586
2    298919
4    298437
Name: count, dtype: int64


Customer Age
 35    59798
 36    59717
 34    59280
 33    59015
 32    57900
       ...
 81        2
-10        2
-11        1
-16        1
 86        1
Name: count, Length: 97, dtype: int64


Customer Location
New Michael           1276
East Michael          1230
South Michael         1226
Port Michael          1219
Lake Michael          1218
                      ...
West Robynhaven          1
Lake Shelleyshire        1
North Terranceport       1
Port Adriennemouth       1
East Ianstad             1
Name: count, Length: 99412, dtype: int64


Device Used
mobile     499624
tablet     498768
desktop    498194
Name: count, dtype: int64


Shipping Address
USCGC Brown\nFPO AE 16210                                   2
USS Sanchez\nFPO AE 14652                                   2
USCGC Holmes\nFPO AA 56289                                  2
USNV Black\nFPO AP 75390                                    2
08240 Veronica Isle Apt. 012\nChristopherville, ID 78042    1
                                                           ..
1624 Smith Ville Suite 721\nHeidiburgh, FL 06942            1
5587 Perez Cove Suite 275\nCindybury, PR 09704              1
522 Terry Squares Apt. 797\nNorth Justinview, NE 43212      1
68140 Kimberly Ports Suite 609\nWest Joshua, AK 24074       1
289 Adams Wells\r\nWest Joeltown, LA 69190                  1
Name: count, Length: 1496582, dtype: int64


Billing Address
USNS Mills\nFPO AE 77203                                  2
USCGC Brown\nFPO AE 16210                                 2
USCGC Holmes\nFPO AA 56289                                2
Unit 8934 Box 0058\nDPO AA 05437                          1
02210 Barnes Village Apt. 174\nNew James, MO 23714        1
                                                         ..
Unit 2815 Box 8978\nDPO AA 91900                          1
1624 Smith Ville Suite 721\nHeidiburgh, FL 06942          1
5587 Perez Cove Suite 275\nCindybury, PR 09704            1
522 Terry Squares Apt. 797\nNorth Justinview, NE 43212    1
289 Adams Wells\r\nWest Joeltown, LA 69190                1
Name: count, Length: 1496583, dtype: int64


Is Fraudulent
0    1421526
1      75060
Name: count, dtype: int64


Account Age Days
11     5191
18     5135
21     5135
15     5123
17     5114
       ...
301    3877
128    3865
300    3850
247    3840
363    3828
Name: count, Length: 365, dtype: int64


Transaction Hour
3     67091
4     66788
2     66730
0     66540
1     66365
5     66281
6     61557
7     61435
12    61266
21    61234
13    61126
11    60961
20    60937
23    60920
8     60918
18    60890
16    60882
14    60863
10    60747
15    60745
19    60698
17    60677
9     60568
22    60367
Name: count, dtype: int64

In [53]:
# chuyển transaction date thành các cột year, month, day, hour, minute, second
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])
df['TransMonth'] = df['Transaction Date'].dt.month
df['TransDay'] = df['Transaction Date'].dt.day
df['TransTime'] = df['Transaction Date'].dt.time
df

,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour,TransMonth,TransDay,TransTime
0,58.09,2024-02-20 05:58:41,bank transfer,electronics,1,17,Amandaborough,tablet,Unit 8934 Box 0058\nDPO AA 05437,Unit 8934 Box 0058\nDPO AA 05437,0,30,5,2,20,05:58:41
1,389.96,2024-02-25 08:09:45,debit card,electronics,2,40,East Timothy,desktop,"634 May Keys\nPort Cherylview, NV 75063","634 May Keys\nPort Cherylview, NV 75063",0,72,8,2,25,08:09:45
2,134.19,2024-03-18 03:42:55,PayPal,home & garden,2,22,Davismouth,tablet,"16282 Dana Falls Suite 790\nRothhaven, IL 15564","16282 Dana Falls Suite 790\nRothhaven, IL 15564",0,63,3,3,18,03:42:55
3,226.17,2024-03-16 20:41:31,bank transfer,clothing,5,31,Lynnberg,desktop,"828 Strong Loaf Apt. 646\nNew Joshua, UT 84798","828 Strong Loaf Apt. 646\nNew Joshua, UT 84798",0,124,20,3,16,20:41:31
4,121.53,2024-01-15 05:08:17,bank transfer,clothing,2,51,South Nicole,tablet,"29799 Jason Hills Apt. 439\nWest Richardtown, ...","29799 Jason Hills Apt. 439\nWest Richardtown, ...",0,158,5,1,15,05:08:17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1496581,53.73,2024-01-26 16:25:05,PayPal,toys & games,5,32,Rebeccafurt,tablet,USNV Clayton\r\nFPO AE 82639,USNV Clayton\r\nFPO AE 82639,0,363,16,1,26,16:25:05
1496582,47.42,2024-02-25 17:03:26,credit card,clothing,4,41,Nataliefort,desktop,"9288 Patricia Cape Apt. 527\r\nMelissaton, IL ...","9288 Patricia Cape Apt. 527\r\nMelissaton, IL ...",0,296,17,2,25,17:03:26
1496583,1045.23,2024-03-28 23:46:47,bank transfer,health & beauty,1,9,East Shannonville,tablet,3015 Elizabeth Summit Suite 819\r\nEast Joelfo...,3015 Elizabeth Summit Suite 819\r\nEast Joelfo...,0,329,23,3,28,23:46:47
1496584,34.25,2024-02-09 11:29:18,debit card,home & garden,2,39,Lake Nicole,mobile,"531 Brittany Pike\r\nNew Stacy, OR 87952","531 Brittany Pike\r\nNew Stacy, OR 87952",0,347,11,2,9,11:29:18
1496585,85.03,2024-01-23 02:46:52,credit card,clothing,4,38,Holtport,tablet,"289 Adams Wells\r\nWest Joeltown, LA 69190","289 Adams Wells\r\nWest Joeltown, LA 69190",0,203,2,1,23,02:46:52

In [55]:
# chỉnh customer location bỏ East, West, North, South, Lake, Central, gom về chung location
df['Customer Location'] = df['Customer Location'].str.replace('East|West|North|South', '', regex=True).str.strip()
df['Customer Location']

0          Amandaborough
1                Timothy
2             Davismouth
3               Lynnberg
4                 Nicole
               ...
1496581      Rebeccafurt
1496582      Nataliefort
1496583     Shannonville
1496584      Lake Nicole
1496585         Holtport
Name: Customer Location, Length: 1496586, dtype: object

In [56]:
df

,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour,TransMonth,TransDay,TransTime
0,58.09,2024-02-20 05:58:41,bank transfer,electronics,1,17,Amandaborough,tablet,Unit 8934 Box 0058\nDPO AA 05437,Unit 8934 Box 0058\nDPO AA 05437,0,30,5,2,20,05:58:41
1,389.96,2024-02-25 08:09:45,debit card,electronics,2,40,Timothy,desktop,"634 May Keys\nPort Cherylview, NV 75063","634 May Keys\nPort Cherylview, NV 75063",0,72,8,2,25,08:09:45
2,134.19,2024-03-18 03:42:55,PayPal,home & garden,2,22,Davismouth,tablet,"16282 Dana Falls Suite 790\nRothhaven, IL 15564","16282 Dana Falls Suite 790\nRothhaven, IL 15564",0,63,3,3,18,03:42:55
3,226.17,2024-03-16 20:41:31,bank transfer,clothing,5,31,Lynnberg,desktop,"828 Strong Loaf Apt. 646\nNew Joshua, UT 84798","828 Strong Loaf Apt. 646\nNew Joshua, UT 84798",0,124,20,3,16,20:41:31
4,121.53,2024-01-15 05:08:17,bank transfer,clothing,2,51,Nicole,tablet,"29799 Jason Hills Apt. 439\nWest Richardtown, ...","29799 Jason Hills Apt. 439\nWest Richardtown, ...",0,158,5,1,15,05:08:17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1496581,53.73,2024-01-26 16:25:05,PayPal,toys & games,5,32,Rebeccafurt,tablet,USNV Clayton\r\nFPO AE 82639,USNV Clayton\r\nFPO AE 82639,0,363,16,1,26,16:25:05
1496582,47.42,2024-02-25 17:03:26,credit card,clothing,4,41,Nataliefort,desktop,"9288 Patricia Cape Apt. 527\r\nMelissaton, IL ...","9288 Patricia Cape Apt. 527\r\nMelissaton, IL ...",0,296,17,2,25,17:03:26
1496583,1045.23,2024-03-28 23:46:47,bank transfer,health & beauty,1,9,Shannonville,tablet,3015 Elizabeth Summit Suite 819\r\nEast Joelfo...,3015 Elizabeth Summit Suite 819\r\nEast Joelfo...,0,329,23,3,28,23:46:47
1496584,34.25,2024-02-09 11:29:18,debit card,home & garden,2,39,Lake Nicole,mobile,"531 Brittany Pike\r\nNew Stacy, OR 87952","531 Brittany Pike\r\nNew Stacy, OR 87952",0,347,11,2,9,11:29:18
1496585,85.03,2024-01-23 02:46:52,credit card,clothing,4,38,Holtport,tablet,"289 Adams Wells\r\nWest Joeltown, LA 69190","289 Adams Wells\r\nWest Joeltown, LA 69190",0,203,2,1,23,02:46:52

In [78]:
#pivot table location và product category
pivot_table = pd.pivot_table(df, values='Transaction Amount', index='Customer Location', columns='Product Category', aggfunc='sum', fill_value=0).astype(float).round(2)
pivot_table

Product Category,clothing,electronics,health & beauty,home & garden,toys & games
Customer Location,,,,,
Aaron,32950.88,28365.53,33911.09,34875.79,32018.65
Aaronberg,3033.71,5637.54,4201.91,6418.82,4365.01
Aaronborough,8627.90,4555.10,4743.19,3734.08,8470.29
Aaronburgh,5642.33,3078.88,3938.56,4944.80,5462.70
Aaronbury,5785.33,5211.36,3963.10,7433.81,2183.04
...,...,...,...,...,...
stad,1613.13,3403.16,1276.43,1630.73,411.10
ton,1668.23,1156.96,1463.71,1440.72,934.89
town,1416.36,5753.72,1006.26,2410.11,1385.61
view,654.96,1402.33,498.52,299.35,1695.91
ville,2002.45,1375.93,1252.22,1030.78,241.37